[theme]
primaryColor = "#005BAC"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202124"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
